default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - wemake-python-styleguide
          - flake8-builtins
          - flake8-annotations-complexity
          - flake8-class-attributes-order
          - flake8-cognitive-complexity

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        pass_filenames: false
        language: python
        entry: bash -c 'make types'

      - id: update-version
        name: update-version
        pass_filenames: false
        language: script
        entry: .github/hooks/update_version.sh

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
