name: Run code style check

on:
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Initialize python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Style checking
        run: make lint
