name: Run tests

on:
  pull_request:
    branches:
      - dev
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements-ci.txt

      - name: Get env file
        uses: n4mespace/get-env-file-from-vault-action@main
        with:
          VAULT_ADDR: ${{ secrets.VAULT_URL }}
          VAULT_USERNAME: ${{ secrets.VAULT_USERNAME }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
          VAULT_SECRETS_PATH: kv/etl/ataman-api/test

      - name: Provide `.env.test` file
        run: cp .env .env.test

      - name: Build Docker images
        run: make docker_build

      - name: Run coverage tests
        run: make test-cov

      - name: Print Coverage
        run: coverage report

      - name: Remove local image
        run: make docker_down
